#!/usr/bin/env node
/**
 * Fetches the latest posts from the public blog RSS feed and writes a static
 * `src/data/blog.ts` module consumed by the Blog section. Runs automatically
 * via the `prebuild` npm script.
 *
 * This script must never fail the build: on any fetch/parse error it falls
 * back to the existing generated file (if present) or writes an empty,
 * type-safe module, and always exits with code 0.
 */
import { writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { XMLParser } from 'fast-xml-parser';

const RSS_URL = 'https://blog.khriztianmoreno.dev/rss.xml';
const OUT_PATH = 'src/data/blog.ts';
const MAX_POSTS = 6;

function stripHtml(input) {
  return String(input ?? '')
    .replace(/<[^>]*>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function truncate(input, maxLength = 160) {
  if (input.length <= maxLength) return input;
  return `${input.slice(0, maxLength).trimEnd()}…`;
}

function toArray(value) {
  if (Array.isArray(value)) return value;
  if (value == null) return [];
  return [value];
}

function buildFileContents(posts) {
  const fetchedAt = new Date().toISOString();
  const serializedPosts = JSON.stringify(posts, null, 2);

  return `// AUTO-GENERATED by scripts/fetch-blog.mjs — do not edit by hand
export interface BlogPost {
  title: string;
  url: string;
  description: string;
  date: string;
  displayDate: string;
}

export const BLOG_FETCHED_AT = '${fetchedAt}';

export const BLOG_POSTS: BlogPost[] = ${serializedPosts};
`;
}

async function writeFallback(reason) {
  if (existsSync(OUT_PATH)) {
    console.warn(`[fetch-blog] ${reason} — keeping existing ${OUT_PATH}`);
    process.exit(0);
    return;
  }

  console.warn(
    `[fetch-blog] ${reason} — writing empty ${OUT_PATH} so the build can type-check`
  );
  await writeFile(OUT_PATH, buildFileContents([]), 'utf8');
  process.exit(0);
}

async function main() {
  let xml;

  try {
    const response = await fetch(RSS_URL, { signal: AbortSignal.timeout(10000) });
    if (!response.ok) {
      throw new Error(`RSS request failed with status ${response.status}`);
    }
    xml = await response.text();
  } catch (error) {
    await writeFallback(`Failed to fetch ${RSS_URL}: ${error.message}`);
    return;
  }

  try {
    // The live feed embeds long article bodies with heavily HTML-escaped
    // code samples, which legitimately exceeds fast-xml-parser's default
    // DoS-mitigation cap of 1000 total entity expansions. Raise it — this is
    // real content, not an entity-expansion attack.
    const parser = new XMLParser({
      ignoreAttributes: false,
      processEntities: { maxTotalExpansions: 20000 },
    });
    const feed = parser.parse(xml);
    const items = toArray(feed?.rss?.channel?.item);

    const posts = items.slice(0, MAX_POSTS).map((item) => {
      const pubDate = new Date(item.pubDate);

      return {
        title: stripHtml(item.title),
        url: item.link,
        description: truncate(stripHtml(item.description)),
        date: pubDate.toISOString(),
        displayDate: new Intl.DateTimeFormat('en', {
          month: 'short',
          year: 'numeric',
        }).format(pubDate),
      };
    });

    await writeFile(OUT_PATH, buildFileContents(posts), 'utf8');
    console.log(`[fetch-blog] Wrote ${posts.length} post(s) to ${OUT_PATH}`);
  } catch (error) {
    await writeFallback(`Failed to parse RSS feed: ${error.message}`);
  }
}

main().catch(async (error) => {
  console.warn(`[fetch-blog] Unexpected error: ${error.message}`);
  process.exit(0);
});
