// AUTO-GENERATED by scripts/fetch-blog.mjs — do not edit by hand
export interface BlogPost {
  title: string;
  url: string;
  description: string;
  date: string;
  displayDate: string;
}

export const BLOG_FETCHED_AT = '2026-07-13T18:26:46.493Z';

export const BLOG_POSTS: BlogPost[] = [
  {
    "title": "The 15 Chrome Updates from Google I/O 2026 We Actually Need to Care About",
    "url": "https://blog.khriztianmoreno.dev/en/posts/15-updates-from-google-io-2026/",
    "description": "Alright folks, Google I/O 2026 just wrapped up, and we need to talk about what they just dropped on us. The writing is on the wall: the \"agentic web\" is officia…",
    "date": "2026-05-19T18:30:34.000Z",
    "displayDate": "May 2026"
  },
  {
    "title": "A better way to build React component libraries",
    "url": "https://blog.khriztianmoreno.dev/en/posts/a-better-way-to-build-react-component-libraries/",
    "description": "Today we'll quickly go over four programming patterns that apply to shared components in React.ReactUsing these allows you to create a well-structured shared co…",
    "date": "2022-07-05T16:01:14.000Z",
    "displayDate": "Jul 2022"
  },
  {
    "title": "A Guide to Efficient Web Testing Workflows",
    "url": "https://blog.khriztianmoreno.dev/en/posts/a-guide-to-efficient-web-testing-workflows/",
    "description": "For senior engineers, web testing isn't about finding bugs—it's about building a system that prevents them. It's an architectural concern. This post outlines se…",
    "date": "2025-12-07T14:56:52.000Z",
    "displayDate": "Dec 2025"
  },
  {
    "title": "A journey to Single Page Applications through React and JavaScript",
    "url": "https://blog.khriztianmoreno.dev/en/posts/a-journey-to-single-page-applications-through-react-and-javascript/",
    "description": "Last June, I had the opportunity to share again in person with the medellinjs community, which I appreciate very much.MedellinJSThis time, I was talking about t…",
    "date": "2022-09-18T14:21:22.000Z",
    "displayDate": "Sep 2022"
  },
  {
    "title": "A practical handbook on JavaScript module systems",
    "url": "https://blog.khriztianmoreno.dev/en/posts/a-practical-handbook-on-javascript-module-systems/",
    "description": "Today I'll give you a practical introduction to the module systems we use when building libraries in JavaScript. As a web application or library grows and more…",
    "date": "2022-06-12T15:34:36.000Z",
    "displayDate": "Jun 2022"
  },
  {
    "title": "A senior stands out for his thinking",
    "url": "https://blog.khriztianmoreno.dev/en/posts/a-senior-stands-out-for-his-thinking/",
    "description": "The analysis of edge cases: a key to evaluating senior developersThe world of programming is constantly changing, but many companies still use outdated evaluati…",
    "date": "2024-12-02T13:28:26.000Z",
    "displayDate": "Dec 2024"
  }
];
